server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  path: "./log"
  stdout: true

database:
  logger:
    path:    "./log"
    level:   "all"
    stdout:  true
  default:
    link:    "mysql:root:root@tcp(127.0.0.1:3306)/StudentManagementSystem"
    debug:   true





